variable "ami_id" {
  description = "The AMI ID generated by Packer"
  type        = string
}

variable "common_tags" {
  description = "Standard resource tags"
  type        = map(string)
  default = {
    Application = "otms"
    Owner       = "Infra-Titans"
    Environment = "dev"
    CostCenter  = "Snaatak"
  }
}
