aws_region    = "us-east-1"
environment   = "dev"
application   = "otms"
owner         = "Infra-Titans"
cost_center   = "Snaatak"
vpc_name      = "dev-otms-vpc"
key_name      = "dev-otms-key"
instance_type = "t3.small"
