variable "ami_id" {
  description = "Attendance API AMI ID generated by Packer"
  type        = string

  validation {
    condition     = can(regex("^ami-[a-zA-Z0-9]+$", var.ami_id))
    error_message = "The ami_id value must be a valid AWS AMI ID starting with ami-."
  }
}



variable "aws_region" {
  type = string
}

variable "environment" {
  type = string
}

variable "application" {
  type = string
}

variable "owner" {
  type = string
}

variable "cost_center" {
  type = string
}

variable "vpc_name" {
  type = string
}


variable "key_name" {
  type = string
}

variable "instance_type" {
  type = string
}

variable "ssm_instance_profile" {
  type        = string
  description = "Name of the manually created IAM Instance Profile for SSM"
}
