variable "aws_region" {
  description = "AWS region where Attendance API resources will be created"
  type        = string
  default     = "us-east-1"
}

variable "ami_id" {
  description = "Attendance API AMI ID generated by Packer"
  type        = string

  validation {
    condition     = can(regex("^ami-[a-zA-Z0-9]+$", var.ami_id))
    error_message = "The ami_id value must be a valid AWS AMI ID starting with ami-."
  }
}

variable "common_tags" {
  description = "Standard tags applied to Attendance API resources"
  type        = map(string)

  default = {
    Application = "otms"
    Owner       = "Infra-Titans"
    Environment = "dev"
    CostCenter  = "Snaatak"
    ManagedBy   = "Terraform"
  }
}
